"""
core/seed_lexicon.py — Seeds the Lexicon database with common Indian bazaar items,
bilingual variations (English, Bengali, Hindi), unit classifications, and colloquial aliases.
"""
import logging
from sqlalchemy.orm import Session
from ..models.lexicon import LexiconEntry, LexiconAlias, LexiconOCRCorrection

logger = logging.getLogger("vaniq.seed")

SEED_LEXICON_DATA = [
    # ── Vegetables (Produce) ──
    {
        "canonical_name": "Potato",
        "hindi_name": "आलू",
        "bengali_name": "গোল আলু",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥔",
        "avg_price_kg": 28.0,
        "aliases": ["alu", "aloo", "batata", "alu 1kg", "potatoes", "alur", "new potato", "jyoti alu", "chandramukhi alu"],
    },
    {
        "canonical_name": "Onion",
        "hindi_name": "प्याज़",
        "bengali_name": "পেঁয়াজ",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🧅",
        "avg_price_kg": 45.0,
        "aliases": ["peyaj", "pyaz", "kanda", "onions", "pyaj", "peyaj 1kg", "nasik pyaz", "bengal onion"],
    },
    {
        "canonical_name": "Tomato",
        "hindi_name": "टमाटर",
        "bengali_name": "টমেটো",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍅",
        "avg_price_kg": 40.0,
        "aliases": ["tamatar", "tometo", "tomatoes", "bilati", "desi tamatar", "hybrid tomato"],
    },
    {
        "canonical_name": "Ginger",
        "hindi_name": "अदरक",
        "bengali_name": "আদা",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🫚",
        "avg_price_kg": 160.0,
        "aliases": ["ada", "adrak", "gingers", "ada 100g", "adrak 250g"],
    },
    {
        "canonical_name": "Garlic",
        "hindi_name": "लहसुन",
        "bengali_name": "রসুন",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🧄",
        "avg_price_kg": 220.0,
        "aliases": ["roshun", "lehsun", "lahsun", "roshun 100g", "garlic pods"],
    },
    {
        "canonical_name": "Green Chilli",
        "hindi_name": "हरी मिर्च",
        "bengali_name": "কাঁচা লঙ্কা",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🌶️",
        "avg_price_kg": 90.0,
        "aliases": ["kancha lanka", "hari mirch", "green chili", "lanka", "mirchi", "kancha lonka"],
    },
    {
        "canonical_name": "Cauliflower",
        "hindi_name": "फूलगोभी",
        "bengali_name": "ফুলকপি",
        "category": "Produce",
        "unit_family": "count",
        "default_unit": "piece",
        "emoji": "🥦",
        "avg_price_kg": 35.0,
        "aliases": ["phulkopi", "phul kopi", "gobhi", "gobi", "cauli", "fulkopi"],
    },
    {
        "canonical_name": "Cabbage",
        "hindi_name": "पत्तागोभी",
        "bengali_name": "বাঁধাকপি",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥬",
        "avg_price_kg": 30.0,
        "aliases": ["badhakopi", "patta gobhi", "patta gobi", "bandhakopi", "cabbages"],
    },
    {
        "canonical_name": "Spinach",
        "hindi_name": "पालक",
        "bengali_name": "পালং শাক",
        "category": "Produce",
        "unit_family": "count",
        "default_unit": "piece",
        "emoji": "🥬",
        "avg_price_kg": 25.0,
        "aliases": ["palong shaak", "palak", "palong saak", "palak saag", "spinach bunch"],
    },
    {
        "canonical_name": "Coriander Leaves",
        "hindi_name": "धनिया पत्ता",
        "bengali_name": "ধনে পাতা",
        "category": "Produce",
        "unit_family": "count",
        "default_unit": "piece",
        "emoji": "🌿",
        "avg_price_kg": 60.0,
        "aliases": ["dhone pata", "dhaniya", "hara dhaniya", "kothmir", "coriander bunch", "dhonepata"],
    },
    {
        "canonical_name": "Brinjal / Eggplant",
        "hindi_name": "बैंगन",
        "bengali_name": "বেগুন",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍆",
        "avg_price_kg": 50.0,
        "aliases": ["begun", "baingan", "eggplant", "aubergine", "gol begun", "lomba begun"],
    },
    {
        "canonical_name": "Cucumber",
        "hindi_name": "खीरा",
        "bengali_name": "শসা",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥒",
        "avg_price_kg": 40.0,
        "aliases": ["shosha", "kheera", "kakdi", "shosa", "cucumbers"],
    },
    {
        "canonical_name": "Carrot",
        "hindi_name": "गाजर",
        "bengali_name": "গাজর",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥕",
        "avg_price_kg": 45.0,
        "aliases": ["gajor", "gajar", "red carrot", "orange carrot"],
    },
    {
        "canonical_name": "Okra / Ladyfinger",
        "hindi_name": "भिंडी",
        "bengali_name": "ঢ্যাঁড়শ",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🫛",
        "avg_price_kg": 55.0,
        "aliases": ["dherosh", "bhindi", "bhendi", "lady finger", "okra", "dhyarosh"],
    },
    {
        "canonical_name": "Pointed Gourd",
        "hindi_name": "परवल",
        "bengali_name": "পটল",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥒",
        "avg_price_kg": 60.0,
        "aliases": ["potol", "parwal", "patol", "pointed gourd"],
    },
    {
        "canonical_name": "Bitter Gourd",
        "hindi_name": "करेला",
        "bengali_name": "করলা",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥒",
        "avg_price_kg": 65.0,
        "aliases": ["korola", "uchhe", "karela", "bitter gourd"],
    },
    {
        "canonical_name": "Bottle Gourd",
        "hindi_name": "लौकी",
        "bengali_name": "লাউ",
        "category": "Produce",
        "unit_family": "count",
        "default_unit": "piece",
        "emoji": "🥒",
        "avg_price_kg": 35.0,
        "aliases": ["lau", "lauki", "kaddu", "bottle gourd", "doodhi"],
    },
    {
        "canonical_name": "Lemon",
        "hindi_name": "नींबू",
        "bengali_name": "পাতিলেবু",
        "category": "Produce",
        "unit_family": "count",
        "default_unit": "piece",
        "emoji": "🍋",
        "avg_price_kg": 5.0,
        "aliases": ["lebu", "nimbu", "patilebu", "lemons", "gondhoraj lebu", "kagzi nimbu"],
    },
    {
        "canonical_name": "Green Peas",
        "hindi_name": "मटर",
        "bengali_name": "মটরশুঁটি",
        "category": "Produce",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🫛",
        "avg_price_kg": 80.0,
        "aliases": ["mator shuti", "matar", "motorshuti", "green peas", "fresh peas"],
    },

    # ── Dairy & Eggs ──
    {
        "canonical_name": "Eggs",
        "hindi_name": "अंडे",
        "bengali_name": "ডিম",
        "category": "Dairy & Eggs",
        "unit_family": "count",
        "default_unit": "piece",
        "emoji": "🥚",
        "avg_price_kg": 7.0,
        "aliases": ["dim", "anda", "egg", "farm egg", "poultry dim", "deshi dim", "dim 12", "dim 6"],
    },
    {
        "canonical_name": "Milk",
        "hindi_name": "दूध",
        "bengali_name": "দুধ",
        "category": "Dairy & Eggs",
        "unit_family": "volume",
        "default_unit": "L",
        "emoji": "🥛",
        "avg_price_kg": 62.0,
        "aliases": ["dudh", "doodh", "amul milk", "mother dairy", "red cow milk", "toned milk", "cow milk"],
    },
    {
        "canonical_name": "Paneer",
        "hindi_name": "पनीर",
        "bengali_name": "পনির",
        "category": "Dairy & Eggs",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🧀",
        "avg_price_kg": 380.0,
        "aliases": ["chhana", "cottage cheese", "amul paneer", "malai paneer", "fresh paneer"],
    },
    {
        "canonical_name": "Curd / Yogurt",
        "hindi_name": "दही",
        "bengali_name": "দই",
        "category": "Dairy & Eggs",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥣",
        "avg_price_kg": 80.0,
        "aliases": ["doi", "dahi", "tok doi", "mishti doi", "curd", "yogurt", "amul dahi"],
    },
    {
        "canonical_name": "Butter",
        "hindi_name": "मक्खन",
        "bengali_name": "মাখন",
        "category": "Dairy & Eggs",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🧈",
        "avg_price_kg": 560.0,
        "aliases": ["makhon", "makhan", "amul butter", "salted butter", "white butter"],
    },
    {
        "canonical_name": "Ghee",
        "hindi_name": "घी",
        "bengali_name": "ঘি",
        "category": "Dairy & Eggs",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🫙",
        "avg_price_kg": 650.0,
        "aliases": ["ghi", "clarified butter", "cow ghee", "jharna ghee", "amul ghee"],
    },

    # ── Cooking Oils & Fats ──
    {
        "canonical_name": "Mustard Oil",
        "hindi_name": "सरसों का तेल",
        "bengali_name": "সরষের তেল",
        "category": "Oils & Fats",
        "unit_family": "volume",
        "default_unit": "L",
        "emoji": "🛢️",
        "avg_price_kg": 145.0,
        "aliases": ["sorsher tel", "sarson ka tel", "mostor tel", "sarson oil", "mustard tel", "sorshe tel", "fortune mustard oil", "kachi ghani"],
    },
    {
        "canonical_name": "Sunflower Oil",
        "hindi_name": "सूरजमुखी तेल",
        "bengali_name": "সূর্যমুখী তেল",
        "category": "Oils & Fats",
        "unit_family": "volume",
        "default_unit": "L",
        "emoji": "🌻",
        "avg_price_kg": 130.0,
        "aliases": ["suryamukhi tel", "sunflower oil", "fortune refined oil", "refined oil", "white oil", "shada tel"],
    },
    {
        "canonical_name": "Soybean Oil",
        "hindi_name": "सोयाबीन तेल",
        "bengali_name": "সোয়াবিন তেল",
        "category": "Oils & Fats",
        "unit_family": "volume",
        "default_unit": "L",
        "emoji": "🌱",
        "avg_price_kg": 125.0,
        "aliases": ["soya oil", "soyabean oil", "soya tel", "fortune soya"],
    },

    # ── Grains, Flours & Pulses ──
    {
        "canonical_name": "Rice",
        "hindi_name": "चावल",
        "bengali_name": "চাল",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍚",
        "avg_price_kg": 52.0,
        "aliases": ["chal", "chawal", "minikit", "gobindobhog", "basmati", "dudhershor", "baskathi", "parboiled rice", "atap chal"],
    },
    {
        "canonical_name": "Atta / Whole Wheat",
        "hindi_name": "आटा",
        "bengali_name": "গমের আটা",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🌾",
        "avg_price_kg": 42.0,
        "aliases": ["atta", "aata", "ashirvaad atta", "chakki atta", "wheat flour", "gomer atta"],
    },
    {
        "canonical_name": "Maida",
        "hindi_name": "मैदा",
        "bengali_name": "ময়দা",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥣",
        "avg_price_kg": 44.0,
        "aliases": ["moyda", "all purpose flour", "flour"],
    },
    {
        "canonical_name": "Besan / Gram Flour",
        "hindi_name": "बेसन",
        "bengali_name": "বেসন",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥣",
        "avg_price_kg": 95.0,
        "aliases": ["besan", "gram flour", "chickpea flour", "chholar besan"],
    },
    {
        "canonical_name": "Masoor Dal",
        "hindi_name": "मसूर दाल",
        "bengali_name": "মসুর ডাল",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍲",
        "avg_price_kg": 110.0,
        "aliases": ["mushur dal", "red lentil", "masoor", "lal dal"],
    },
    {
        "canonical_name": "Moong Dal",
        "hindi_name": "मूँग दाल",
        "bengali_name": "মুগ ডাল",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍲",
        "avg_price_kg": 125.0,
        "aliases": ["mug dal", "muger dal", "yellow moong", "dhua moong", "bhaja muger dal"],
    },
    {
        "canonical_name": "Toor Dal",
        "hindi_name": "अरहर दाल",
        "bengali_name": "অড়হর ডাল",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍲",
        "avg_price_kg": 160.0,
        "aliases": ["arhar dal", "arhar", "toor", "tur dal", "pigeon pea"],
    },
    {
        "canonical_name": "Chana Dal",
        "hindi_name": "चना दाल",
        "bengali_name": "ছোলার ডাল",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍲",
        "avg_price_kg": 105.0,
        "aliases": ["chholar dal", "chana dal", "bengal gram dal"],
    },
    {
        "canonical_name": "Poha / Flattened Rice",
        "hindi_name": "पोहा",
        "bengali_name": "চিঁড়ে",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🥣",
        "avg_price_kg": 60.0,
        "aliases": ["chire", "poha", "chivda", "flattened rice"],
    },
    {
        "canonical_name": "Puffed Rice / Muri",
        "hindi_name": "मुरमुरा",
        "bengali_name": "মুড়ি",
        "category": "Grains & Pulses",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍿",
        "avg_price_kg": 50.0,
        "aliases": ["muri", "murmura", "kurmura", "puffed rice"],
    },

    # ── Spices & Pantry ──
    {
        "canonical_name": "Poppy Seeds / Posto",
        "hindi_name": "खसखस",
        "bengali_name": "পোস্ত",
        "category": "Spices",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🌱",
        "avg_price_kg": 1800.0,
        "aliases": ["posto", "khus khus", "khuskhus", "poppy seeds", "posto 100g", "posto 50g"],
    },
    {
        "canonical_name": "Turmeric Powder",
        "hindi_name": "हल्दी पाउडर",
        "bengali_name": "হলুদ গুঁড়ো",
        "category": "Spices",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🟡",
        "avg_price_kg": 240.0,
        "aliases": ["holud", "haldi", "haldi powder", "holud gundo", "sunrise holud", "everest haldi"],
    },
    {
        "canonical_name": "Red Chilli Powder",
        "hindi_name": "लाल मिर्च पाउडर",
        "bengali_name": "লঙ্কা গুঁড়ো",
        "category": "Spices",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🔴",
        "avg_price_kg": 320.0,
        "aliases": ["lanka gundo", "lal mirch", "mirch powder", "deggi mirch", "kashmiri mirch"],
    },
    {
        "canonical_name": "Cumin Seeds",
        "hindi_name": "जीरा",
        "bengali_name": "জিরে",
        "category": "Spices",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🫙",
        "avg_price_kg": 360.0,
        "aliases": ["jeera", "jire", "sabut jeera", "gota jire", "cumin"],
    },
    {
        "canonical_name": "Salt",
        "hindi_name": "नमक",
        "bengali_name": "নুন / লবণ",
        "category": "Pantry",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🧂",
        "avg_price_kg": 28.0,
        "aliases": ["noon", "namak", "tata salt", "lobon", "salt 1kg", "sendha namak"],
    },
    {
        "canonical_name": "Sugar",
        "hindi_name": "चीनी",
        "bengali_name": "চিনি",
        "category": "Pantry",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍬",
        "avg_price_kg": 46.0,
        "aliases": ["chini", "cheeni", "sugar 1kg", "white sugar"],
    },
    {
        "canonical_name": "Tea Leaves",
        "hindi_name": "चाय पत्ती",
        "bengali_name": "চা পাতা",
        "category": "Pantry",
        "unit_family": "mass",
        "default_unit": "kg",
        "emoji": "🍵",
        "avg_price_kg": 380.0,
        "aliases": ["cha pata", "chai patti", "tea", "tata tea", "red label", "wagh bakri", "darjeeling tea"],
    },
]

# Common OCR misread pairings to pre-seed
SEED_OCR_CORRECTIONS = [
    ("besaw", "Besan / Gram Flour"),
    ("atia", "Atta / Whole Wheat"),
    ("alv", "Potato"),
    ("alue", "Potato"),
    ("pevaj", "Onion"),
    ("pyaaz", "Onion"),
    ("tamtr", "Tomato"),
    ("tomto", "Tomato"),
    ("sorshe", "Mustard Oil"),
    ("mostor", "Mustard Oil"),
    ("chwl", "Rice"),
    ("chaoal", "Rice"),
    ("dhim", "Eggs"),
    ("dud", "Milk"),
    ("dhone", "Coriander Leaves"),
]


def seed_lexicon_if_empty(db: Session) -> int:
    """Checks if lexicon table is empty and seeds initial entries and aliases."""
    count = db.query(LexiconEntry).count()
    if count > 0:
        logger.info(f"[Lexicon] Already seeded with {count} entries.")
        return count

    logger.info("[Lexicon] Seeding initial Indian grocery lexicon...")
    created = 0
    entry_map = {}

    for item in SEED_LEXICON_DATA:
        entry = LexiconEntry(
            canonical_name=item["canonical_name"],
            hindi_name=item.get("hindi_name"),
            bengali_name=item.get("bengali_name"),
            category=item.get("category"),
            unit_family=item.get("unit_family"),
            default_unit=item.get("default_unit"),
            emoji=item.get("emoji"),
            avg_price_kg=item.get("avg_price_kg"),
        )
        db.add(entry)
        db.flush()
        entry_map[entry.canonical_name] = entry.id
        created += 1

        # Add aliases
        for alias in item.get("aliases", []):
            db.add(LexiconAlias(
                entry_id=entry.id,
                raw_alias=alias.lower().strip(),
                source="seed",
                confidence=1.0,
                confirmed_count=5,
            ))

    # Seed OCR corrections
    for misread, target_name in SEED_OCR_CORRECTIONS:
        target_id = entry_map.get(target_name)
        if target_id:
            db.add(LexiconOCRCorrection(
                misread=misread.lower().strip(),
                corrected=target_name,
                entry_id=target_id,
                frequency=10,
            ))

    db.commit()
    logger.info(f"[Lexicon] Successfully seeded {created} items with aliases & corrections.")
    return created
